# Copyright (C)  2022 devloops
# Use of this software is govered by the Business Source License included in the LICENSE.TXT file and at www.mariadb.com/bsl11.
#
# Change Date:
#
# On the date above, in accordance with the Business Source License, use of this software will be governed by the open source license specified in the LICENSE.TXT file.

load("@rules_cc//cc:defs.bzl", "cc_binary")
package(default_visibility = ["//visibility:public"])


cc_binary(
    name = "pack",
    srcs = ["main.cc"],
    deps = [

    ],
    #   copts = [
    # "-std=c++20", "-O3", "-fopenmp", "-finline-functions",
    # "-m64", "-funroll-loops", "-fvectorize","-flto", "-fopenmp-use-tls","-fopenmp-simd",
    # ],
)